# cars.py
cars_data = {
    'audi-a4': {
        'modelo': 'A4',
        'marca': 'Audi',
        'anio': 2023,
        'precio': '$42,000',
        'garantia': '4 años',
        'imagen': 'AudiA4.jpg',
        'descripcion': 'El Audi A4 combina elegancia, tecnología y rendimiento en un sedán premium. Con un interior lujoso y lleno de innovación, ofrece una experiencia de conducción superior.',
        'motor': '2.0L TFSI de 4 cilindros',
        'potencia': '201 hp',
        'velocidad_max': '210 km/h',
        'tanque_gasolina': '54 L',
        'transmision': 'S tronic de 7 velocidades',
        'traccion': 'Tracción integral quattro'
    },
    'bmw-m3': {
        'modelo': 'M3 Competition',
        'marca': 'BMW',
        'anio': 2024,
        'precio': '$85,000',
        'garantia': '5 años',
        'imagen': 'bmwm3competition.png',
        'descripcion': 'El BMW M3 Competition es sinónimo de deportividad y potencia. Su motor de altas revoluciones y su chasis deportivo te garantizan emociones fuertes en cada curva.',
        'motor': '3.0L TwinPower Turbo de 6 cilindros en línea',
        'potencia': '503 hp',
        'velocidad_max': '290 km/h',
        'tanque_gasolina': '59 L',
        'transmision': 'M Steptronic de 8 velocidades',
        'traccion': 'Tracción trasera'
    },
    'chevrolet-corvette': {
        'modelo': 'Corvette C8',
        'marca': 'Chevrolet',
        'anio': 2022,
        'precio': '$70,000',
        'garantia': '3 años',
        'imagen': 'chevroletcorvettec8.png',
        'descripcion': 'El Chevrolet Corvette C8 rompe esquemas con su motor central y su diseño aerodinámico. Un superdeportivo americano accesible que no sacrifica rendimiento ni estilo.',
        'motor': '6.2L LT2 V8',
        'potencia': '495 hp',
        'velocidad_max': '312 km/h',
        'tanque_gasolina': '70 L',
        'transmision': 'DCT de 8 velocidades',
        'traccion': 'Tracción trasera'
    },
    'dodge-challenger': {
        'modelo': 'Challenger SRT',
        'marca': 'Dodge',
        'anio': 2021,
        'precio': '$60,000',
        'garantia': '4 años',
        'imagen': 'dodgechallengersrt.png',
        'descripcion': 'El Dodge Challenger SRT es un auténtico muscle car. Su potente motor V8 y su estética retro lo convierten en un coche para los amantes de la velocidad y el diseño clásico.',
        'motor': '6.4L HEMI V8',
        'potencia': '485 hp',
        'velocidad_max': '290 km/h',
        'tanque_gasolina': '70 L',
        'transmision': 'Automática de 8 velocidades',
        'traccion': 'Tracción trasera'
    },
    'ford-f150-raptor': {
        'modelo': 'F-150 Raptor',
        'marca': 'Ford',
        'anio': 2023,
        'precio': '$75,000',
        'garantia': '4 años',
        'imagen': 'fordf-150raptor.png',
        'descripcion': 'La Ford F-150 Raptor es la reina del off-road. Con su suspensión de alto rendimiento y su potente motor, está lista para conquistar cualquier terreno sin esfuerzo.',
        'motor': '3.5L EcoBoost V6',
        'potencia': '450 hp',
        'velocidad_max': '180 km/h',
        'tanque_gasolina': '136 L',
        'transmision': 'Automática de 10 velocidades',
        'traccion': 'Tracción en las cuatro ruedas'
    },
    'honda-civic': {
        'modelo': 'Civic Type R',
        'marca': 'Honda',
        'anio': 2023,
        'precio': '$38,000',
        'garantia': '2 años',
        'imagen': 'hondacivictyper.png',
        'descripcion': 'El Honda Civic Type R es el hatchback deportivo definitivo. Su diseño agresivo y su motor turbo ofrecen una experiencia de conducción emocionante y precisa en la carretera.',
        'motor': '2.0L VTEC Turbo de 4 cilindros',
        'potencia': '315 hp',
        'velocidad_max': '272 km/h',
        'tanque_gasolina': '47 L',
        'transmision': 'Manual de 6 velocidades',
        'traccion': 'Tracción delantera'
    },
    'mercedes-benz-c-class': {
        'modelo': 'C-Class',
        'marca': 'Mercedes-Benz',
        'anio': 2023,
        'precio': '$55,000',
        'garantia': '4 años',
        'imagen': 'mercedesbenzc-class.png',
        'descripcion': 'El Mercedes-Benz C-Class es el epítome del lujo y la sofisticación. Su diseño elegante, su interior de alta calidad y su tecnología avanzada lo convierten en el sedán perfecto.',
        'motor': '2.0L Turbo de 4 cilindros',
        'potencia': '255 hp',
        'velocidad_max': '240 km/h',
        'tanque_gasolina': '66 L',
        'transmision': '9G-Tronic de 9 velocidades',
        'traccion': 'Tracción trasera'
    },
    'ford-mustang': {
        'modelo': 'Mustang GT',
        'marca': 'Ford',
        'anio': 2022,
        'precio': '$45,000',
        'garantia': '3 años',
        'imagen': 'mustanggtford.png',
        'descripcion': 'El Ford Mustang GT es un ícono americano. Con su poderoso motor V8, su rugido inconfundible y su estilo inconfundible, es la definición de un coche deportivo legendario.',
        'motor': '5.0L Coyote V8',
        'potencia': '450 hp',
        'velocidad_max': '250 km/h',
        'tanque_gasolina': '61 L',
        'transmision': 'Manual de 6 velocidades',
        'traccion': 'Tracción trasera'
    },
    'nissan-gtr': {
        'modelo': 'GT-R',
        'marca': 'Nissan',
        'anio': 2020,
        'precio': '$110,000',
        'garantia': '3 años',
        'imagen': 'nissangt-r.png',
        'descripcion': 'El Nissan GT-R, conocido como "Godzilla", es una máquina de ingeniería japonesa. Su tracción integral y su motor biturbo le permiten competir con cualquier superdeportivo del mundo.',
        'motor': '3.8L V6 Twin-Turbo',
        'potencia': '565 hp',
        'velocidad_max': '315 km/h',
        'tanque_gasolina': '74 L',
        'transmision': 'DCT de 6 velocidades',
        'traccion': 'Tracción integral'
    },
    'subaru-wrx': {
        'modelo': 'WRX STI',
        'marca': 'Subaru',
        'anio': 2020,
        'precio': '$37,000',
        'garantia': '3 años',
        'imagen': 'subaruwrxsti.png',
        'descripcion': 'El Subaru WRX STI es un rally car para la calle. Su motor boxer, su tracción integral simétrica y su chasis deportivo lo convierten en el coche ideal para los entusiastas de la conducción.',
        'motor': '2.5L BOXER Turbo de 4 cilindros',
        'potencia': '310 hp',
        'velocidad_max': '255 km/h',
        'tanque_gasolina': '60 L',
        'transmision': 'Manual de 6 velocidades',
        'traccion': 'Tracción integral'
    },
    'tesla-model-3': {
        'modelo': 'Model 3',
        'marca': 'Tesla',
        'anio': 2024,
        'precio': '$48,000',
        'garantia': '5 años',
        'imagen': 'teslamodel3.png',
        'descripcion': 'El Tesla Model 3 es el futuro de la movilidad. Con su motor eléctrico, su diseño minimalista y su tecnología de vanguardia, ofrece una conducción silenciosa, potente y sin emisiones.',
        'motor': 'Motor eléctrico',
        'potencia': '283 hp',
        'velocidad_max': '225 km/h',
        'tanque_gasolina': 'N/A',
        'transmision': 'Transmisión de una sola velocidad',
        'traccion': 'Tracción trasera'
    },
    'toyota-supra': {
        'modelo': 'Supra',
        'marca': 'Toyota',
        'anio': 2021,
        'precio': '$52,000',
        'garantia': '2 años',
        'imagen': 'toyotasupra.png',
        'descripcion': 'El Toyota Supra es una leyenda renacida. Con su diseño aerodinámico, su potente motor de seis cilindros y su manejo deportivo, es un coche que honra su legado.',
        'motor': '3.0L Twin-Scroll Turbo de 6 cilindros en línea',
        'potencia': '382 hp',
        'velocidad_max': '250 km/h',
        'tanque_gasolina': '52 L',
        'transmision': 'Automática de 8 velocidades',
        'traccion': 'Tracción trasera'
    }
}